JD Sample Libraries: /home/ktemkin/Documents/Projects/JD-sample-libraries/sample_twi_tsl2561.c File Reference
/home/ktemkin/Documents/Projects/JD-sample-libraries/sample_twi_tsl2561.c File Reference
#include "twi/master.h"
#include "uart/stdio.h"
#include <util/delay.h>
Data Structures
union light_sensor_reading_union
Typedefs
typedef union
light_sensor_reading_union light_sensor_reading
Functions
int main ()
Typedef Documentation
typedef union light_sensor_reading_union light_sensor_reading
Definition at line 46 of file sample_twi_tsl2561.c.
Function Documentation
int main ()
Small section of sample code, for the Atmega328p.
Definition at line 52 of file sample_twi_tsl2561.c.
References end_twi_packet(), light_sensor_reading_union::full, light_sensor_reading_union::high, LastByte, light_sensor_reading_union::low, perform_bus_pirate_twi_command(), read_via_twi(), send_via_twi(), set_up_stdio_over_serial(), set_up_twi_hardware(), start_twi_read_from(), and start_twi_write_to().
            {
   uint8_t start_code, device_id;
   light_sensor_reading reading;
   //Set up stdio over the device's UART.
   set_up_stdio_over_serial();
   //Set up the microcontrollers's I2C hardware, running at 100kHz.
   set_up_twi_hardware(100000);
   _delay_ms(1);
   //Enable the sensor's internal ADC.
   //Note that we're using almost exactly the same command as used when communicating
   //via Bus Pirate-- there's only one small difference: the last "r" has been replaced with an "s",
   //indicating that we expect no further data.
   perform_bus_pirate_twi_command("[ 0x72 0x80 0x03 [ 0x73 s ]", &start_code);
   //If the two LSBs of the start code were 0b11, we've started the device successfully!
   if((start_code & 0x03) == 0x03) {
     printf("Sensor enabled succesfully!\n");
   }
   //Read the device's ID. For this example, we'll use the special "w" syntax, a special form of "write"
   //which accepts the value to be transmitted as an argument. This allows convenient programmatic control
   //of values to be transmitted!
   perform_bus_pirate_twi_command("[ 0x72 w [ 0x73 s ]", 0x8A, &device_id);
   printf("Read device ID: 0x%x\n", device_id);
   //Alternatively, one can implement the I2C communications manually, rather
   //than in bus pirate format. This is almost always faster!
   //
   //Realistically, you'd want these constants abstracted to somewhere else
   //in non-demonstation code.
   start_twi_write_to(0x39);
   send_via_twi(0x8A);
   start_twi_read_from(0x39);
   device_id = read_via_twi(LastByte);
   end_twi_packet();
   printf("Re-read device ID: 0x%x\n", device_id);
   //And take repeated light sensor readings.
   while(1) {
     perform_bus_pirate_twi_command("[ 0x72 0xAC [ 0x73 r s ]", &reading.low, &reading.high);
     printf("Sensor reading: %u\n", reading.full);
     _delay_ms(100);
   }
   return 0;
 }