JD Sample Libraries: /home/ktemkin/Documents/Projects/JD-sample-libraries/uart/stdio.c File Reference
stdio.c File Reference
#include "stdio.h"
Macros
#define USART_STATUS UCSR0A
#define READY_TO_TRANSMIT UDRE0
#define DATA_RECIEVED RXC0
#define USE_EIGHT_BIT_DATA
Functions
void set_up_stdio_over_serial ()
void initialize_uart ()
void send_via_uart (char c)
char receieve_via_uart ()
Macro Definition Documentation
#define DATA_RECIEVED RXC0
Definition at line 13 of file stdio.c.
#define READY_TO_TRANSMIT UDRE0
Definition at line 12 of file stdio.c.
#define USART_STATUS UCSR0A
EECE 387 Example Code AVR Standard I/O over UART: Universal Asynchronous Receiver / Transmitter
Allows you to use printf/scanf using your AVR and a USB-to-serial converter, like the Bus Pirate. If you're about to use this to gather debug information, you might want to see if the Logic Analyzer isn't a better fit to your needs.
Definition at line 11 of file stdio.c.
#define USE_EIGHT_BIT_DATA
Definition at line 15 of file stdio.c.
Function Documentation
void initialize_uart ()
Sets up the raw UART (Universal Asynchronous Receiver/Transmitter) for general use. Does not set up the UART for use with stdin/stdout/stderr.
Definition at line 50 of file stdio.c.
Referenced by set_up_stdio_over_serial().
{
     //These values are automatically generated by <util/setbaud.h>
     //They're a tad
     UBRR0H = UBRRH_VALUE;
     UBRR0L = UBRRL_VALUE;
     #if USE_2X
       UCSR0A |= _BV(U2X0);
     #else
       UCSR0A &= ~(_BV(U2X0));
     #endif
     //Set up use of 8-bit data packets...
     UCSR0C = (1 << UCSZ01) | (1 << UCSZ00);
     //And take ownership of the Rx/Tx lines on the AVR.
     UCSR0B = (1 << RXEN0)  | (1 << TXEN0);
 }
char receieve_via_uart ()
Waits for and recieves a single character over the serial line.
This kind of function is known as a "blocking" function– as execution can't continue until it's complete!
Definition at line 84 of file stdio.c.
{
   wait_until_data_is_received();
   return read_contents_of_receive_buffer();
 }
void send_via_uart (char c)
Sends the provided character over the serial line.
Definition at line 73 of file stdio.c.
{
   wait_until_ready_to_transmit();
   place_into_transmit_buffer(c);
 }
void set_up_stdio_over_serial ()
Sets up the device to use STDIO over serial.
Definition at line 41 of file stdio.c.
References initialize_uart().
Referenced by main().
{
     initialize_uart();
     set_up_special_files();
 }